version: "3.7"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - tomcat-data:/opt/tomcat/webapps
    networks:
      - conceptpower-network
    env_file:
      - ./config/db.env
  conceptpower:
    build:
        dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - conceptpower-network
    depends_on:
      - "db"

networks:
  conceptpower-network:

volumes:
  db-data:
    external: true
  tomcat-data:
    external: true