version: "3.7"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    volumes:
      - cp-db-data:/var/lib/mysql
    networks:
      - conceptpower-network
    env_file:
      - ./config/db.env
  conceptpower-docker:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - conceptpower-network
    depends_on:
      - "db"
    volumes:
      - path/to/cp/data:/app

networks:
  conceptpower-network:

volumes:
  cp-db-data:
    external: true
